cp -rv fake_wavs/ fake_wavs_2/
cp -rv fake_wavs/ fake_wavs_3/
cp -rv fake_wavs/ fake_wavs_4/
cp -rv fake_wavs/ fake_wavs_5/
cp -rv fake_wavs/ fake_wavs_6/
cp -rv fake_wavs/ fake_wavs_7/
cp -rv fake_wavs/ fake_wavs_8/
cp -rv fake_wavs/ fake_wavs_9/
cp -rv fake_wavs/ fake_wavs_10/
cp -rv fake_wavs/ fake_wavs_11/
cp -rv fake_wavs/ fake_wavs_12/
cp -rv fake_wavs/ fake_wavs_13/
cp -rv fake_wavs/ fake_wavs_14/
cp -rv fake_wavs/ fake_wavs_15/
cp -rv fake_wavs/ fake_wavs_16/
cp -rv fake_wavs/ fake_wavs_17/
cp -rv fake_wavs/ fake_wavs_18/
cp -rv fake_wavs/ fake_wavs_19/
cp -rv fake_wavs/ fake_wavs_20/
cp -rv fake_wavs/ fake_wavs_21/
cp -rv fake_wavs/ fake_wavs_22/
cp -rv fake_wavs/ fake_wavs_23/
cp -rv fake_wavs/ fake_wavs_24/
cp -rv fake_wavs/ fake_wavs_25/
cp -rv fake_wavs/ fake_wavs_26/
cp -rv fake_wavs/ fake_wavs_27/
cp -rv fake_wavs/ fake_wavs_28/
